### ISSUE TITLE
Create a validation check for pincodes

### ISSUE THREAD

**Issue by yellowwoods12** [Awesome-React-Modules/React-Pincode#23]
As of now, when a wrong pincode is entered the input field turns red. There is no type check for various kind of wrong inpiuts. For example, a pincode must be of 6 digits. So if some number less than or greater than that is entered an alert should display.
Similarly if alphabets are entered then a specific alert should display for it as well and so on.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue @yellowwoods12

**Comment by plxity** [comment]
@yellowwoods12 or let's not allow a user to enter anything except numbers?

**Comment by Xtremilicious** [comment]
I have worked on this validation aspect before, so it won't be a problem for me. I am confident I can do it:)

**Comment by shreyakapoor08** [comment]
I want to work on this issue
