### ISSUE TITLE
Changes in the data retrieved for the API used in the project.

### ISSUE THREAD

**Issue by arpit9667** [Awesome-React-Modules/React-Pincode#26]
Currently, the project is using the "Region" parameter of the response to fill the City field. The results will be more accurate if instead of "Region", the "District" parameter is used.

**Comment by adityabisoi** [comment]
@arpit9667 I can work on this issue. Can you please assign me? Thanks.

**Comment by adityabisoi** [comment]
To make this more accurate, can we add another field, so that there'll be three fields-

`Field: Parameter`
------------------------
`Town/City: name`
`District: district`
`State: state`

**Comment by adityabisoi** [comment]
@Xtremilicious According to Gssoc rules, you should only work on issues after some confirmation/ assignment. @arpit9667 Is it okay if people work and close the issues other participants are interested in but haven't been assigned yet?

**Comment by Xtremilicious** [comment]
@adityabisoi @arpit9667 I noticed that some issues have assigned members, but it has not been updated/fixed even though the issue difficulty level is low. I think that people who are able to do it should be allowed for a pull request even though they are not assigned.

Please share your views @arpit9667 @plxity

**Comment by plxity** [comment]
This program is aimed to help beginners. As many of the participants are new to open source. They should be given time to solve the issue. GSSoC has defined the flow for contributing to the program and we should follow that.

I really appreciate your efforts in solving an issue @Xtremilicious
You can raise a PR for this now. But in coming future take care of this. Don't work on the issue until it is assigned to you. 

I hope it is clear now @adityabisoi @Xtremilicious
Thanks.

**Comment by Xtremilicious** [comment]
Thanks for the conformation @plxity Will keep that in mind:)

**Comment by siddhishree** [comment]
Has this issue been assigned? Or can I work on this?

**Comment by Xtremilicious** [comment]
@plxity this issue has been resolved in PR #29

**Comment by plxity** [comment]
Fixed #29
