### ISSUE TITLE
Improve documentation/ README.md for better understanding.

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Pincode#3]

**Comment by habeeba-naaz** [comment]
I am gssoc20 participant..I am interested to do this work...please assign me and provide further details

**Comment by adityabisoi** [comment]
@plxity I want to work on this issue.

**Comment by plxity** [comment]
We have to add the following things:
1) Add the link to the npm module
2) Add better images
3) Add more images showing different usage of props (not all, only some)
4) Include the technology or framework used in this module.

**Comment by habeeba-naaz** [comment]
Okay sure

**Comment by habeeba-naaz** [comment]
Any format...?

**Comment by plxity** [comment]
Just maintain the current format. Nothing fancy is required.

**Comment by habeeba-naaz** [comment]
Okay...thank you

**Comment by plxity** [comment]
@habeeba-naaz Yes sure.

**Comment by yellowwoods12** [comment]
Hi @habeeba-naaz, are you working on this one? Let us know.

**Comment by habeeba-naaz** [comment]
Yes...I am working. I installed react pincode module.after that I kept when I am linking to react pincode getting error....I kept message in slack..so waiting for reply

**Comment by Xtremilicious** [comment]
@habeeba-naaz make sure the module folder is the root folder. e.g. Pincode-master on your Desktop.

If you keep the module inside a folder which has digits in its name, e.g. Pincode-3424, the build may not be successful. Hope this helps.

**Comment by shreyakapoor08** [comment]
Can I take up this issue

**Comment by plxity** [comment]
@habeeba-naaz are you working on this? Or should @shreyakapoor08 take this up?

**Comment by habeeba-naaz** [comment]
Okay please give it to shreya Kapoor.But I thought after I complete css of input fields , taking images of it..

**Comment by habeeba-naaz** [comment]
I am working on css input fields and then post images in README

**Comment by habeeba-naaz** [comment]
Actually this issue is interlinked with my issue regarding css input fields...I thought after I complete that issue thought of working on it... But as she was searching for issues you can proceed to give her that issue

**Comment by plxity** [comment]
@shreyakapoor08 I have assigned the issue to you.

**Comment by Kuljeet-123** [comment]
Hii @plxity  I'm a GSSOC'20 participant ..can i work on this issue too.

**Comment by plxity** [comment]
@Kuljeet-123  It is already assigned to @shreyakapoor08 .

**Comment by plxity** [comment]
> @shreyakapoor08 I have assigned the issue to you.

@shreyakapoor08 Any updates?

**Comment by shreyakapoor08** [comment]
yeah i am working on it.

**Comment by shreyakapoor08** [comment]
@plxity I have raised the PR. Kindly check and let me know if any corrections are required.
