### ISSUE TITLE
Adding Code of Conduct.md & CONTRIBUTING.md

### ISSUE THREAD

**Issue by shreyakapoor08** [Awesome-React-Modules/React-Pincode#40]
There is no Code of Conduct as of now. I have mentioned in one of the points in readme regarding it.
So can I make a file named Code of Conduct ?

**Comment by yellowwoods12** [comment]
@shreyakapoor08 Yes go ahead!

**Comment by plxity** [comment]
@shreyakapoor08 Also add CONTRIBUTING.md file in the same PR.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Also add CONTRIBUTING.md file in the same PR.

As in two issues in the same branch right? and the  raise the PR for it?

**Comment by amanintech** [comment]
Yes right

**Comment by plxity** [comment]
> > @shreyakapoor08 Also add CONTRIBUTING.md file in the same PR.
> 
> As in two issues in the same branch right? and the raise the PR for it?

It is the same issue just that two different task in it.

**Comment by shreyakapoor08** [comment]
Okay got it :)

**Comment by shreyakapoor08** [comment]
> > > @shreyakapoor08 Also add CONTRIBUTING.md file in the same PR.
> > 
> > 
> > As in two issues in the same branch right? and the raise the PR for it?
> 
> It is the same issue just that two different task in it.

Hey I have done both the tasks. Please check and let me know if any corrections are required.

**Comment by shreyakapoor08** [comment]
@plxity Included the files in readme.md , Please check
