### ISSUE TITLE
Adding Contributions.md

### ISSUE THREAD

**Issue by shreyakapoor08** [Awesome-React-Modules/React-Pincode#41]
Can I work on this, so that the participants can get a clear understanding of how to contribute to the website.

**Comment by yellowwoods12** [comment]
Hey @shreyakapoor08, if it is for the webisite then the issue should be on the website's repo. I am closing this issue here, opening one on the website and assigning it to you.

**Comment by shreyakapoor08** [comment]
Okay please do that
