### ISSUE TITLE
feat: add places for better accuracy

### ISSUE THREAD

**Issue by adityabisoi** [Awesome-React-Modules/React-Pincode#42]
Currently, the `city` field displays `district` data from API end-point, which is inaccurate.
From the API end-point, we can add more fields-

`Field : Parameter`
------------------------
`Town/City : name`
`District : district`
`State : state`

Where `field` is the displayed data and `parameter` are data from API.

**Comment by adityabisoi** [comment]
I can work on this. Thanks.

**Comment by plxity** [comment]
@adityabisoi Go ahead.
