### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by AdityaSrivast** [Awesome-React-Modules/React-Pincode#46]
Add pull request template for the repository
Refer:
- https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

Include fields like, Issue related, Demo Link, Screenshots, etc.

**Comment by abhu-A-J** [comment]
Can I take this?

**Comment by AdityaSrivast** [comment]
@abhu-A-J sure. Go ahead :rocket:
