### ISSUE TITLE
Improve error handling functionality when pincode is not correct.

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Pincode#5]

**Comment by adityabisoi** [comment]
@plxity can you please provide some details? Is it to give a warning when the pin code is incorrect instead of merely changing box color to red? I want to work on this issue. Please assign this to me. Thanks.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue

**Comment by Satzyakiz** [comment]
I would like to contribute to this issue as a part of GSSoC 2020.

**Comment by plxity** [comment]
As of now when a wrong pin code is entered, the border of the pin code input field becomes red. But the user has no idea what went wrong? So I am looking for an alternative solution.

**Comment by ashishnagpal2498** [comment]
If no such pin code matches , the response of the API would be null , so we can show a message that the pin code entered is invalid.

**Comment by plxity** [comment]
@ashishnagpal2498 How are you planning to show a message?

**Comment by ashishnagpal2498** [comment]
Either we can add a tag on the top of search , controlled by state that if the pin code is invalid the warning shows or we can remove the city and state divs and display warning there. Whichever is suitable to you.

**Comment by yellowwoods12** [comment]
I think an alert would work that would pop up when a wrong pincode is entered and closing it would make the pincode field empty so that it can be used again.

**Comment by Xtremilicious** [comment]
Working on it!

**Comment by plxity** [comment]
@yellowwoods12 Displaying an error as the focus is lost is a good idea? What do you suggest?

**Comment by Xtremilicious** [comment]
@plxity kindly check my solution.

**Comment by Xtremilicious** [comment]
@plxity this issue has been resolved in PR #29

**Comment by plxity** [comment]
Fixed #29

**Comment by ashishnagpal2498** [comment]
I think this is bit unfair as issue wasn't assigned to anybody and I was discussing it as well as constantly keeping a check for the issue to be assigned to me. @plxity
