### ISSUE TITLE
Add TOC to README.md

### ISSUE THREAD

**Issue by jamesjose03** [Awesome-React-Modules/React-Pincode#51]
- The README is a long one. Adding a Table of Contents will make it easier for navigating through it.

**Comment by jamesjose03** [comment]
I am a GSSOC participant. I would like to work on this issue

**Comment by jamesjose03** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/31133182/77503740-648e3080-6e84-11ea-9e76-93dae426283c.png)

**Comment by jamesjose03** [comment]
@AdityaSrivast Can I work on this issue?

**Comment by plxity** [comment]
@jamesjose03 Assigned to you.

**Comment by jamesjose03** [comment]
Thank you. Am working on it 👍
