### ISSUE TITLE
Addition of Actions

### ISSUE THREAD

**Issue by abhu-A-J** [Awesome-React-Modules/React-Pincode#55]
Add appropriate actions to do the following tasks:

- Actions to detect stale issues and PR and give labels to them. ( Issue and PR which are unattended for long time)
- Auto Assign reviewers to PR created so they get notified about them.
- Detect any foul language/behaviour.

@plxity @yellowwoods12  Do you think it's a good idea to add these to the repo??

**Comment by yellowwoods12** [comment]
@abhu-A-J  Yes, that sounds good. Go ahead!

**Comment by prangya244** [comment]
I would like to work on it.

**Comment by plxity** [comment]
@prangya244 It is already assigned to @abhu-A-J
