### ISSUE TITLE
Implement a website for users to experince & try this module.

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Pincode#6]

**Comment by adityabisoi** [comment]
@plxity I want to work on this issue. Please assign this to me. Thank you.

**Comment by plxity** [comment]
@adityabisoi How do you plan to do it?

**Comment by adityabisoi** [comment]
@plxity We can create a new react app and include all the project files there since I have seen that the project contains only core files, and doesn't have a script to start the app. Thus, ```npm start``` would fire up the server and the project can be used.

**Comment by adityabisoi** [comment]
@plxity Am I good to go on this? Please confirm.

**Comment by plxity** [comment]
@adityabisoi Where would you plan to host the website?

**Comment by adityabisoi** [comment]
@plxity Heroku would be great.

**Comment by plxity** [comment]
@adityabisoi Netlify will be a good option, I guess. 
I am assigning you the issue.

**Comment by AkbarHabeeb** [comment]
Good one, Do we really need a site. We can add a code sandbox which shows our package with example. Can you please add more about it?

**Comment by adityabisoi** [comment]
@plxity Here is the website https://clever-montalcini-e7adf1.netlify.com/

**Comment by yellowwoods12** [comment]
> @plxity Here is the website https://clever-montalcini-e7adf1.netlify.com/

Hey @adityabisoi, it looks good. I think an about section at the top of the website with a link to the github repo will be great.  @plxity What do you think about it?

**Comment by adityabisoi** [comment]
@yellowwoods12 @plxity Sure. I'm using react build for production, instead of webpack. Is that okay?

**Comment by plxity** [comment]
@yellowwoods12 Yes, that's a good idea. It will make the site informative.

**Comment by plxity** [comment]
@adityabisoi Yeah, it is okay.

**Comment by adityabisoi** [comment]
@plxity @yellowwoods12 I have made the changes, see it on https://react-pincode.netlify.com/

**Comment by Xtremilicious** [comment]
While the website works, I believe it should have a good UI and be more informative which explains the features of the module with different pages/routes for official documentation. Kindly have a look at [react-credit-cards](https://ovvwzkzry9.codesandbox.io) as an example for the demo website.

**Comment by adityabisoi** [comment]
@Xtremilicious Yes I am well aware of the UI, but since the task is a medium-level with implementation only, I need confirmation on its scope from the mentors first.

**Comment by plxity** [comment]
@adityabisoi It looks fine. But make the following changes to make the site more informative.

1) Add "fork me banner" on the top.
2) Make the UI better.
3) Increase the size of the input field.
4) Give proper padding between the input field.
4) Make the edges round.

As @Xtremilicious said, the UI should be good.  
1) Adding a footer is necessary.
2) And information about how it works.
3) Add a link of the NPM website and readme.md file of GitHub.

**Comment by adityabisoi** [comment]
@plxity I have updated the website. The website now features:
* Improved UI
* Footer
* Link to npm package, options to star, fork and view instructions on GitHub

**Comment by adityabisoi** [comment]
Please review.

**Comment by plxity** [comment]
@adityabisoi The website looks great. :+1: . Please raise PR for the same.

**Comment by yellowwoods12** [comment]
@adityabisoi good work!

**Comment by plxity** [comment]
@adityabisoi Any updates?
