### ISSUE TITLE
Add the link of Codepen implementation of the module in README.md

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Pincode#7]

**Comment by samidhaVerma** [comment]
Hey, I think I will take this up: any specific requirements in the implementation?

**Comment by plxity** [comment]
@samidhaVerma No specific requirements. Just a simple flow would do.

**Comment by siddhishree** [comment]
Hey, Can I work on this issue?

**Comment by plxity** [comment]
@siddhishree Yes, sure.

**Comment by plxity** [comment]
@siddhishree What is the progress?

**Comment by siddhishree** [comment]
Working on it. Would be done by tonight.

**Comment by siddhishree** [comment]
@plxity I am done with my side of the work but issue #26 hasn't been merged yet which might lead to inconsistencies. So should I make my PR or wait for issue #26?

**Comment by plxity** [comment]
@siddhishree Wait for the issue #26 to get merged.

**Comment by siddhishree** [comment]
@plxity Issue #26 has been merged. So I think my PR is good to go.

**Comment by siddhishree** [comment]
@plxity The issue is not labeled as anyone of beginner, easy, medium or hard and hence my score hasn't been updated. Can you please add a suitable label?

**Comment by plxity** [comment]
@siddhishree Yes sure.
